[project]
version = "0.1"
name = "topico_api_model"

dependencies = [
    "pydantic==2.11.7"
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

#[tool.setuptools.packages.find]
#where = ["src"]
